# THIS DOCKERFILE IS INTENDED FOR DEVELOPMENT ENVIRONMENTS
# DO NOT USE THIS FOR PRODUCTION USAGES.

version: '3'

services:
  postgresql:
    image: docker.io/bitnami/postgresql:16
    ports:
      - '5431:5432'
    hostname: postgresql
    networks:
      - prisma-network
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_DATABASE=angency-me
      - POSTGRESQL_USERNAME=agency-admin
      - POSTGRESQL_PASSWORD=password
networks:
  prisma-network:
    name: prisma-network
volumes:
  postgresql_data:
    driver: local
